### ISSUE TITLE
Where is the MTE and PAC implementation?

### ISSUE THREAD

**Issue by 040840308** [mit-ll/HAKC#1]
Hi, 

       I read the PMCPass.cpp carefully, however, I cannot find the implementation part about MTE (such as memory tagging for every malloc call) and PAC (such as MAC generation for every pointer). How are these two techniques implemented during this project?

       Thanks

**Comment by deadly-platypus** [comment]
Hi,

The exists to insert our HAKC checks within the kernel code during compilation, as well as perform the checks and transfers needed for compartment transfers.  The transfers of dynamically allocated data are manually inserted.  All of this functionality are actually contained in kernel functions, so if you look at `MTE-kernel/arch/arm64/kernel/hakc/hakc.c` you will see the PAC and MTE instructions.

**Comment by 040840308** [comment]
> Hi,
> 
> The exists to insert our HAKC checks within the kernel code during compilation, as well as perform the checks and transfers needed for compartment transfers. The transfers of dynamically allocated data are manually inserted. All of this functionality are actually contained in kernel functions, so if you look at `MTE-kernel/arch/arm64/kernel/hakc/hakc.c` you will see the PAC and MTE instructions.

OK, got it.
